# main.yml

# 工作流程的名字
name: Test, Build and Release apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - v*

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v2
      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v1.1.1
        with:
          channel: "stable"
          flutter-version: "2.2.x"
      # 下载项目依赖
      - run: flutter pub get
      # 执行测试
      - run: flutter test
      # 打包 APK
      - run: flutter build apk --release
      # 生成change-log
      - name: generate change-log
        uses: rcmachado/changelog-action@v1
        with:
          args: fmt
      # 发布到 Release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/apk/release/*.apk
          body_path: ${{ github.workspace }}-CHANGELOG.md
            # note you'll typically need to create a personal access token
            # with permissions to create releases in the other repo
          token: ${{ secrets.TOKEN }}